### ISSUE TITLE
Error running on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by radiantly** [niftylettuce/forward-email#134]
Running the forward-mail package on Ubuntu 18.04 LTS on a GCP virtual machine fails because of some semver error because the python version installed is Python 2.7.15rc1

Will elaborate and post stack trace when I reach home.

**Comment by niftylettuce** [comment]
Please see our README for python-spfcheck2 and python-dkim-verify requirements.

**Comment by radiantly** [comment]
@niftylettuce Am I missing something obvious? I installed the requirements for python-spfcheck2 and python-dkim-verify.
```
/home/myuser/forward-email/node_modules/semver/semver.js:323
    throw new TypeError('Invalid Version: ' + version)
    ^

TypeError: Invalid Version: 2.7.15rc1
    at new SemVer (/home/myuser/forward-email/node_modules/semver/semver.js:323:11)
    at Range.test (/home/myuser/forward-email/node_modules/semver/semver.js:1203:15)
    at Function.satisfies (/home/myuser/forward-email/node_modules/semver/semver.js:1257:16)
    at Object.<anonymous> (/home/myuser/forward-email/node_modules/python-dkim-verify/index.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/myuser/forward-email/index.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

**Comment by niftylettuce** [comment]
I think the `rc1` is throwing off `semver`

**Comment by niftylettuce** [comment]
Let me know how it goes.  niftylettuce@gmail.com ❤️

**Comment by radiantly** [comment]
Seems like a `semver.coerce` fixes this issue. I've opened the needed PRs, could you review them?

**Comment by niftylettuce** [comment]
Actually, I like `semver.coerce` better.  I've fixed this in both packages we use internally and also version bumped them.  Thanks so much @radiantly for the nice fix.
