### ISSUE TITLE
Could we run the Self-Hosted Windows?

### ISSUE THREAD

**Issue by nhvu1988** [niftylettuce/forward-email#138]
Hi, I'm trying to setup forward-email on windows server 2016 but still don't know how to run it correctly. These are all steps done
1. latest node installed (version 12.3.1)
2. install pm2 using `npm install -g pm2`
3. create a folder and install forward-email using `npm install https://github.com/niftylettuce/forward-email`
4. create an index.js file with content from [Programmatic Usage](https://github.com/niftylettuce/forward-email#programmatic-usage)
5. try to run `node index.js` and gets the error 

```
node .\index.js
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'auto-bind'
Require stack:
- C:\inetpub\wwwroot\forward-email\node_modules\forward-email\index.js
- C:\inetpub\wwwroot\forward-email\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\inetpub\wwwroot\forward-email\node_modules\forward-email\index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\inetpub\wwwroot\forward-email\index.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\inetpub\\wwwroot\\forward-email\\node_modules\\forward-email\\index.js',
    'C:\\inetpub\\wwwroot\\forward-email\\index.js'
  ]
}
```

Could anyone help me? Thanks

**Comment by radiantly** [comment]
I'm not sure what your problem is, but you can do a `npm install forward-email` since there have been npm releases since v2.

**Comment by nhvu1988** [comment]
@radiantly I installed it already since you can see the error is line 11 inside the index.js file of forward-email module
```
at Object.<anonymous> (C:\inetpub\wwwroot\forward-email\node_modules\forward-email\index.js:11:18)
```

and it says `Error: Cannot find module 'auto-bind'` that it should be installed when installing `forward-email` module?

**Comment by radiantly** [comment]
Could you `git clone https://github.com/niftylettuce/forward-email`, `npm i` and then `node index.js` to see if you get the same error?
