### ISSUE TITLE
Error Signing with DKIM

### ISSUE THREAD

**Issue by felipecorrea9** [niftylettuce/forward-email#86]
Hi, I manage to get it working on a Centos Distro, using the API version (not with PM2), but Im getting an error when I get emails. 

`[2019-01-21 18:58:40] INFO  SMTP Server listening on [::]:25
[2019-01-21 19:00:17] INFO  [#fwaryfkco73mtdad] Connection from mail-lj1-f181.google.com
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] S: 220 boris ESMTP
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] C: EHLO mail-lj1-f181.google.com
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] S: 250-boris Nice to meet you, mail-lj1-f181.google.com
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] 250-PIPELINING
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] 250-8BITMIME
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] 250-SMTPUTF8
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] 250-STARTTLS
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] 250 SIZE 26214400
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] C: STARTTLS
[2019-01-21 19:00:17] DEBUG [#fwaryfkco73mtdad] S: 220 Ready to start TLS
[2019-01-21 19:00:18] INFO  [#fwaryfkco73mtdad] Connection upgraded to TLS using  ECDHE-RSA-AES128-GCM-SHA256
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] C: EHLO mail-lj1-f181.google.com
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] S: 250-boris Nice to meet you, mail-lj1-f181.google.com
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] 250-PIPELINING
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] 250-8BITMIME
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] 250-SMTPUTF8
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] 250 SIZE 26214400
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] C: MAIL FROM:<user@somemail.com> SIZE=5638
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] S: 250 Accepted
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] C: RCPT TO:<hello@mymail.cl>
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] S: 250 Accepted
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] C: DATA
[2019-01-21 19:00:18] DEBUG [#fwaryfkco73mtdad] S: 354 End data with <CR><LF>.<CR><LF>
[2019-01-21 19:00:19] DEBUG Creating transport: nodemailer (5.1.1; +https://nodemailer.com/; SMTP/5.1.1[client:5.1.1])
[2019-01-21 19:00:19] DEBUG Sending mail using SMTP/5.1.1[client:5.1.1]
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] Resolved aspmx.l.google.com as 173.194.204.26 [cache miss]
[2019-01-21 19:00:19] INFO  [BDhBGrdfsyo] Connection established to 173.194.204.26:25
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 220 mx.google.com ESMTP b1si13291557qtr.173 - gsmtp
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] C: EHLO server.server.om
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-mx.google.com at your service, [x.x.x.x]
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-SIZE 157286400
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-8BITMIME
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-STARTTLS
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-ENHANCEDSTATUSCODES
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-PIPELINING
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-CHUNKING
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250 SMTPUTF8
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] C: STARTTLS
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 220 2.0.0 Ready to start TLS
[2019-01-21 19:00:19] INFO  [BDhBGrdfsyo] Connection upgraded with STARTTLS
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] C: EHLO server.server.com
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-mx.google.com at your service, [x.x.x.x]
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-SIZE 157286400
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-8BITMIME
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-ENHANCEDSTATUSCODES
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-PIPELINING
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250-CHUNKING
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250 SMTPUTF8
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] SMTP handshake finished
[2019-01-21 19:00:19] INFO  Sending message <CA+-rjvHHHzW4JJ1b2yvFP32ruWs9rL6x8zkWw9W4jnDn=r-3Mw@mail.gmail.com> to <user2@othermail.com>
[2019-01-21 19:00:19] DEBUG Signing outgoing message with 1 keys
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] C: MAIL FROM:<user@somemail.com>
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] S: 250 2.1.0 OK b1si13291557qtr.173 - gsmtp
[2019-01-21 19:00:19] DEBUG [BDhBGrdfsyo] C: RCPT TO:<user2@othermail.com>
punycode.js:73
        const parts = string.split('@');
                             ^

TypeError: Cannot read property 'split' of undefined
    at mapDomain (punycode.js:73:23)
    at Object.toASCII (punycode.js:406:9)
    at generateDKIMHeader (/usr/lib/node_modules/nodemailer/lib/dkim/sign.js:58:25)
    at module.exports (/usr/lib/node_modules/nodemailer/lib/dkim/sign.js:34:22)
    at signNextKey (/usr/lib/node_modules/nodemailer/lib/dkim/index.js:114:29)
    at DKIMSigner.sendSignedOutput (/usr/lib/node_modules/nodemailer/lib/dkim/index.js:128:20)
    at RelaxedBody.relaxedBody.on (/usr/lib/node_modules/nodemailer/lib/dkim/index.js:191:18)
    at RelaxedBody.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by felipecorrea9** [comment]
Never Mind, I was doing something wroge, now it works.

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
